include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'build/**'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5

  metrics-exclude:
    - test/**
    - lib/di/**
  rules-exclude:
    - test/**
    - lib/di/**

  extends:
    - package:dart_code_metrics_presets/all.yaml
  rules:
    - avoid-ignoring-return-values: false
    - arguments-ordering:
        child-last: true
    - prefer_relative_imports: true
  anti-patterns:
    - long-method
    - long-parameter-list
