name: workout_buddy_finder
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: 3.2.3
  collection: 1.16.0
  cloud_firestore: 4.2.0
  cupertino_icons: 1.0.5
  dart_geohash: 2.0.2
  dio: 4.0.6
  either_dart: 0.3.0
  equatable: 2.0.5
  firebase_auth: 4.2.4
  firebase_core: 2.4.1
  firebase_storage: 11.0.10
  flutter_bloc: 8.1.1
  flutter_hooks: 0.18.5+1
  font_awesome_flutter: 10.3.0
  freezed_annotation: 2.2.0
  get_it: 7.2.0
  geocoding: 2.0.5
  geolocator: 9.0.2
  go_router: 6.0.0
  google_fonts: 3.0.1
  google_sign_in: 5.4.2
  http: 0.13.5
  image_picker: 0.8.6          # Used to select images from the User's device image library or take a new photo using the camera
  image_cropper: 3.0.1
  injectable: 2.0.1
  json_annotation: 4.7.0
  sn_progress_dialog: 1.0.9
  swipable_stack: 2.0.0
  url_launcher: 6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.2
  freezed: 2.3.2
  injectable_generator: 2.0.1
  dart_code_metrics: 5.0.1
  json_serializable: 6.5.4
  flutter_launcher_icons: 0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_logo.png

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/app_logo.png'
  min_sdk_android: 21
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/icon/app_logo.png'
