name: workout_buddy_finder
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: 3.2.3
  dio: 4.0.6
  either_dart: 0.3.0
  equatable: 2.0.5
  firebase_auth: 4.1.5
  firebase_core: 2.3.0
  font_awesome_flutter: 10.2.1
  flutter_bloc: 8.1.1
  get_it: 7.2.0
  go_router: 5.2.0
  google_fonts: 3.0.1
  injectable: 2.0.1
  json_annotation: 4.7.0
  url_launcher: 6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.2
  injectable_generator: 2.0.1
  dart_code_metrics: 5.0.1
  json_serializable: 6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_logo.png