// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4E5hFPIcG8ETo_tkrna4MbEIFU40ut9o',
    appId: '1:246633292825:android:6406ab446b15f6a7253688',
    messagingSenderId: '246633292825',
    projectId: 'workout-buddy-finder',
    storageBucket: 'workout-buddy-finder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7YslBLSlrmz9OB0qLernep35FdBaMuRg',
    appId: '1:246633292825:ios:5c2789e1c3446df5253688',
    messagingSenderId: '246633292825',
    projectId: 'workout-buddy-finder',
    storageBucket: 'workout-buddy-finder.appspot.com',
    androidClientId: '246633292825-f551ggoa3b6fnji5ug7cmmse6ieks6fn.apps.googleusercontent.com',
    iosClientId: '246633292825-op360rk740c0q86lf857u8plinfb50hu.apps.googleusercontent.com',
    iosBundleId: 'com.islamdidarmd.workout-buddy-finder',
  );
}
